name: app
type: nodejs:16

disk: 1024

dependencies:
  nodejs:
    'npm': '*'

relationships:
  database: 'db:postgresql'
  metadatastore: 'metadatastore:redis'

hooks:
  build: !include
    type: string
    path: ops/hooks/build.sh
  deploy: !include
    type: string
    path: ops/hooks/deploy.sh
  post_deploy: !include
    type: string
    path: ops/hooks/post_deploy.sh

web:
  locations:
    '/':
      root: public
      allow: true
      scripts: false
      index: ['index.html']
      rules:
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          expires: 4w

  commands:
    start: !include
      type: string
      path: ops/start.sh 

mounts:
  # A writable mount for the data directory 
  '/data':
    source: local
    source_path: 'data'

source:
  operations:
    auto-update:
      command: |
        curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0

